import db from '../db/index.js';
import { jsonSuccess, jsonError } from '../utils/response.js';
import { normalizeUrl } from '../utils/urlNormalize.js';

/**
 * 导出 JSON 格式数据
 * 包含所有分类及其链接
 */
export function exportJSON(req, res) {
  try {
    const categories = db.prepare(
      'SELECT * FROM categories WHERE deleted_at IS NULL ORDER BY sort_order ASC, id ASC'
    ).all();

    const result = {
      version: 1,
      exported_at: new Date().toISOString(),
      categories: [],
    };

    for (const cat of categories) {
      const links = db.prepare(
        'SELECT * FROM links WHERE category_id = ? AND deleted_at IS NULL ORDER BY sort_order ASC, id ASC'
      ).all(cat.id);

      result.categories.push({
        id: cat.id,
        name: cat.name,
        subtitle: cat.subtitle,
        emoji: cat.emoji,
        bg_color: cat.bg_color,
        sort_order: cat.sort_order,
        links: links.map(link => ({
          id: link.id,
          name: link.name,
          url: link.url,
          domain: link.domain,
          avatar_text: link.avatar_text,
          avatar_color: link.avatar_color,
          is_pinned: link.is_pinned,
          pin_order: link.pin_order,
          sort_order: link.sort_order,
        })),
      });
    }

    res.setHeader('Content-Type', 'application/json; charset=utf-8');
    res.setHeader('Content-Disposition', 'attachment; filename="cozy-nav-export.json"');
    res.send(JSON.stringify(result, null, 2));
  } catch (e) {
    // 不向客户端泄露内部错误细节，仅输出到日志
    console.log(`[${new Date().toISOString()}] [导出] [JSON] [失败] ${e.message}`);
    jsonError(res, '导出失败，请稍后重试');
  }
}

/**
 * 导出浏览器书签 HTML 格式
 */
export function exportBookmarks(req, res) {
  try {
    const categories = db.prepare(
      'SELECT * FROM categories WHERE deleted_at IS NULL ORDER BY sort_order ASC, id ASC'
    ).all();

    let html = `<!DOCTYPE NETSCAPE-Bookmark-file-1>
<!-- This is an automatically generated file. -->
<!-- Generated by Cozy Nav -->
<META HTTP-EQUIV="Content-Type" CONTENT="text/html; charset=UTF-8">
<TITLE>Cozy Nav Bookmarks</TITLE>
<H1>Cozy Nav Bookmarks</H1>
<DL><p>
`;

    for (const cat of categories) {
      const links = db.prepare(
        'SELECT * FROM links WHERE category_id = ? AND deleted_at IS NULL ORDER BY sort_order ASC, id ASC'
      ).all(cat.id);

      if (links.length === 0) continue;

      const title = `${cat.emoji || '📁'} ${escapeHtml(cat.name)}`;
      const addDate = Math.floor(Date.now() / 1000);

      html += `  <DT><H3 ADD_DATE="${addDate}">${title}</H3>\n`;
      html += `  <DL><p>\n`;

      for (const link of links) {
        html += `    <DT><A HREF="${escapeHtml(link.url)}" ADD_DATE="${addDate}">${escapeHtml(link.name)}</A>\n`;
      }

      html += `  </DL><p>\n`;
    }

    html += `</DL><p>`;

    res.setHeader('Content-Type', 'text/html; charset=utf-8');
    res.setHeader('Content-Disposition', 'attachment; filename="cozy-nav-bookmarks.html"');
    res.send(html);
  } catch (e) {
    // 不向客户端泄露内部错误细节，仅输出到日志
    console.log(`[${new Date().toISOString()}] [导出] [HTML] [失败] ${e.message}`);
    jsonError(res, '导出失败，请稍后重试');
  }
}

/**
 * 导入 JSON 数据
 * 支持跳过重复或覆盖现有
 */
export function importJSON(req, res) {
  const { body } = req;
  const { strategy = 'skip' } = req.body;

  if (!body || !body.categories) {
    return jsonError(res, '无效的 JSON 格式');
  }

  const { categories } = body;
  const stats = { categories: 0, links: 0, skipped: 0 };

  try {
    db.exec('BEGIN');

    for (const cat of categories) {
      if (!cat.name) continue;

      // 查找是否已存在同名分类
      let existingCat = db.prepare('SELECT * FROM categories WHERE name = ? AND deleted_at IS NULL').get(cat.name);
      let catId;

      if (existingCat && strategy === 'skip') {
        catId = existingCat.id;
      } else if (existingCat && strategy === 'overwrite') {
        // 覆盖策略：将分类下旧链接软删除（保留历史数据，可恢复），随后重新导入
        db.prepare('UPDATE links SET deleted_at = ? WHERE category_id = ? AND deleted_at IS NULL').run(new Date().toISOString(), existingCat.id);
        catId = existingCat.id;
        existingCat = null;
      } else {
        // 新增分类（未显式传排序权重时自动排到末尾）
        const info = db.prepare(
          'INSERT INTO categories (name, subtitle, emoji, bg_color, sort_order) VALUES (?, ?, ?, ?, ?)'
        ).run(
          cat.name,
          cat.subtitle || '',
          cat.emoji || '📁',
          cat.bg_color || 'slate',
          cat.sort_order ?? db.prepare('SELECT COALESCE(MAX(sort_order), 0) + 1 AS next FROM categories WHERE deleted_at IS NULL').get().next
        );
        catId = info.lastInsertRowid;
        stats.categories++;
      }

      // 导入链接
      if (Array.isArray(cat.links)) {
        for (const link of cat.links) {
          if (!link.name || !link.url) continue;

          // 检查链接是否已存在：优先按 URL 规范化指纹判重，无法规范化时回退精确匹配
          const normalized = normalizeUrl(link.url);
          const existingLink = normalized
            ? db.prepare(
                'SELECT * FROM links WHERE category_id = ? AND url_normalized = ? AND deleted_at IS NULL'
              ).get(catId, normalized)
            : db.prepare(
                'SELECT * FROM links WHERE category_id = ? AND url = ? AND deleted_at IS NULL'
              ).get(catId, link.url);

          if (existingLink && strategy === 'skip') {
            stats.skipped++;
            continue;
          }

          if (existingLink && strategy === 'overwrite') {
            db.prepare(
              'UPDATE links SET name = ?, domain = ?, avatar_text = ?, avatar_color = ? WHERE id = ?'
            ).run(
              link.name,
              extractDomain(link.url),
              link.avatar_text || link.name[0],
              link.avatar_color || 'slate',
              existingLink.id
            );
            stats.links++;
          } else {
            // 新增链接（未显式传排序权重时自动排到该分类末尾）
            db.prepare(
              `INSERT INTO links (category_id, name, url, domain, avatar_text, avatar_color, is_pinned, sort_order, url_normalized)
               VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)`
            ).run(
              catId,
              link.name,
              link.url,
              extractDomain(link.url),
              link.avatar_text || link.name[0],
              link.avatar_color || 'slate',
              link.is_pinned || 0,
              link.sort_order ?? db.prepare('SELECT COALESCE(MAX(sort_order), 0) + 1 AS next FROM links WHERE category_id = ? AND deleted_at IS NULL').get(catId).next,
              normalized
            );
            stats.links++;
          }
        }
      }
    }

    db.exec('COMMIT');
    jsonSuccess(res, stats, `导入成功：新增 ${stats.categories} 个分类，${stats.links} 个链接，跳过 ${stats.skipped} 个重复`);
  } catch (e) {
    db.exec('ROLLBACK');
    // 不向客户端泄露内部错误细节，仅输出到日志
    console.log(`[${new Date().toISOString()}] [导入] [失败] ${e.message}`);
    jsonError(res, '导入失败，请检查数据后重试');
  }
}

/**
 * 导入浏览器书签 HTML
 */
export function importBookmarks(req, res) {
  const { body } = req;
  const { strategy = 'skip' } = req.body;
  const { html } = body;

  if (!html) {
    return jsonError(res, '请提供 HTML 内容');
  }

  try {
    const parsed = parseBookmarkHTML(html);
    const stats = { categories: 0, links: 0, skipped: 0 };

    db.exec('BEGIN');

    for (const folder of parsed.folders) {
      if (!folder.name || folder.links.length === 0) continue;

      // 查找是否已存在同名分类
      let existingCat = db.prepare('SELECT * FROM categories WHERE name = ? AND deleted_at IS NULL').get(folder.name);
      let catId;

      if (existingCat && strategy === 'skip') {
        catId = existingCat.id;
      } else if (existingCat && strategy === 'overwrite') {
        // 覆盖策略：将分类下旧链接软删除（保留历史数据，可恢复），随后重新导入
        db.prepare('UPDATE links SET deleted_at = ? WHERE category_id = ? AND deleted_at IS NULL').run(new Date().toISOString(), existingCat.id);
        catId = existingCat.id;
        existingCat = null;
      } else {
        const info = db.prepare(
          'INSERT INTO categories (name, emoji, bg_color, sort_order) VALUES (?, ?, ?, ?)'
        ).run(folder.name, '📁', 'slate', db.prepare('SELECT COALESCE(MAX(sort_order), 0) + 1 AS next FROM categories WHERE deleted_at IS NULL').get().next);
        catId = info.lastInsertRowid;
        stats.categories++;
      }

      // 导入链接
      for (const link of folder.links) {
        if (!link.name || !link.url) continue;

        // 检查链接是否已存在：优先按 URL 规范化指纹判重，无法规范化时回退精确匹配
        const normalized = normalizeUrl(link.url);
        const existingLink = normalized
          ? db.prepare(
              'SELECT * FROM links WHERE category_id = ? AND url_normalized = ? AND deleted_at IS NULL'
            ).get(catId, normalized)
          : db.prepare(
              'SELECT * FROM links WHERE category_id = ? AND url = ? AND deleted_at IS NULL'
            ).get(catId, link.url);

        if (existingLink && strategy === 'skip') {
          stats.skipped++;
          continue;
        }

        if (existingLink && strategy === 'overwrite') {
          db.prepare(
            'UPDATE links SET name = ?, domain = ?, avatar_text = ? WHERE id = ?'
          ).run(link.name, extractDomain(link.url), link.name[0], existingLink.id);
          stats.links++;
        } else {
          // 新增链接（未显式传排序权重时自动排到该分类末尾）
          db.prepare(
            `INSERT INTO links (category_id, name, url, domain, avatar_text, avatar_color, sort_order, url_normalized)
             VALUES (?, ?, ?, ?, ?, ?, ?, ?)`
          ).run(catId, link.name, link.url, extractDomain(link.url), link.name[0], 'slate', db.prepare('SELECT COALESCE(MAX(sort_order), 0) + 1 AS next FROM links WHERE category_id = ? AND deleted_at IS NULL').get(catId).next, normalized);
          stats.links++;
        }
      }
    }

    db.exec('COMMIT');
    jsonSuccess(res, stats, `导入成功：新增 ${stats.categories} 个分类，${stats.links} 个链接，跳过 ${stats.skipped} 个重复`);
  } catch (e) {
    db.exec('ROLLBACK');
    // 不向客户端泄露内部错误细节，仅输出到日志
    console.log(`[${new Date().toISOString()}] [导入] [失败] ${e.message}`);
    jsonError(res, '导入失败，请检查数据后重试');
  }
}

/**
 * 解析浏览器书签 HTML
 */
function parseBookmarkHTML(html) {
  const folders = [];
  
  // 使用简单的字符串解析，正则提取 H3 标题和 DT 链接
  // 移除注释
  const cleanedHtml = html.replace(/<!--[\s\S]*?-->/g, '');
  
  // 按 H3 分割文件夹
  const h3Regex = /<H3[^>]*>([\s\S]*?)<\/H3>/gi;
  let match;
  let lastIndex = 0;
  
  while ((match = h3Regex.exec(cleanedHtml)) !== null) {
    // 获取 H3 之后到下一个 H3 或结束之间的内容
    const folderName = match[1].replace(/<[^>]*>/g, '').trim();
    const startPos = h3Regex.lastIndex;
    
    // 找下一个 H3
    const nextMatch = h3Regex.exec(cleanedHtml);
    const endPos = nextMatch ? nextMatch.index : cleanedHtml.length;
    
    const folderContent = cleanedHtml.substring(startPos, endPos);
    
    // 提取 DT 链接
    const linkRegex = /<A\s+HREF="([^"]*)"[^>]*>([\s\S]*?)<\/A>/gi;
    let linkMatch;
    const links = [];
    
    while ((linkMatch = linkRegex.exec(folderContent)) !== null) {
      links.push({
        url: linkMatch[1],
        name: linkMatch[2].replace(/<[^>]*>/g, '').trim(),
      });
    }
    
    // 清理文件夹名称（移除 emoji 前缀）
    const cleanName = folderName.replace(/^[^\w\u4e00-\u9fff]*/, '').trim() || folderName;
    
    if (cleanName && links.length > 0) {
      folders.push({ name: cleanName, links });
    }
    
    lastIndex = endPos;
    if (!nextMatch) break;
  }
  
  return { folders };
}

/**
 * 提取域名
 */
function extractDomain(url) {
  try {
    return new URL(url).hostname;
  } catch {
    return '';
  }
}

/**
 * HTML 转义
 */
function escapeHtml(str) {
  return str.replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#39;');
}