import db from '../db/index.js';
import { jsonSuccess, jsonError } from '../utils/response.js';
import { normalizeUrl } from '../utils/urlNormalize.js';
import { writeLog, LOG_MODULE, LOG_ACTION } from '../utils/operationLogger.js';

/**
 * 导出 JSON 格式数据
 * 包含所有分类及其链接
 */
export function exportJSON(req, res) {
  try {
    const categories = db.prepare(
      'SELECT * FROM categories WHERE deleted_at IS NULL ORDER BY sort_order ASC, id ASC'
    ).all();

    const result = {
      version: 1,
      exported_at: new Date().toISOString(),
      categories: [],
    };

    for (const cat of categories) {
      const links = db.prepare(
        'SELECT * FROM links WHERE category_id = ? AND deleted_at IS NULL ORDER BY sort_order ASC, id ASC'
      ).all(cat.id);

      result.categories.push({
        id: cat.id,
        name: cat.name,
        subtitle: cat.subtitle,
        emoji: cat.emoji,
        bg_color: cat.bg_color,
        sort_order: cat.sort_order,
        links: links.map(link => ({
          id: link.id,
          name: link.name,
          url: link.url,
          domain: link.domain,
          avatar_text: link.avatar_text,
          avatar_color: link.avatar_color,
          is_pinned: link.is_pinned,
          pin_order: link.pin_order,
          is_favorite: link.is_favorite,
          sort_order: link.sort_order,
        })),
      });
    }

    res.setHeader('Content-Type', 'application/json; charset=utf-8');
    res.setHeader('Content-Disposition', 'attachment; filename="cozy-nav-export.json"');
    res.send(JSON.stringify(result, null, 2));
    // 操作日志：导出为敏感操作，留痕便于事后追溯数据外流
    const linkCount = result.categories.reduce((sum, c) => sum + c.links.length, 0);
    writeLog({
      module: LOG_MODULE.IMPORT,
      action: LOG_ACTION.EXPORT,
      detail: `导出书签数据（JSON）：${result.categories.length} 个分类、${linkCount} 个书签`,
      meta: { format: 'json', categories: result.categories.length, links: linkCount },
    }, req);
  } catch (e) {
    // 不向客户端泄露内部错误细节，仅输出到日志
    console.log(`[${new Date().toISOString()}] [导出] [JSON] [失败] ${e.message}`);
    jsonError(res, '导出失败，请稍后重试');
  }
}

/**
 * 导出浏览器书签 HTML 格式
 */
export function exportBookmarks(req, res) {
  try {
    const categories = db.prepare(
      'SELECT * FROM categories WHERE deleted_at IS NULL ORDER BY sort_order ASC, id ASC'
    ).all();

    let html = `<!DOCTYPE NETSCAPE-Bookmark-file-1>
<!-- This is an automatically generated file. -->
<!-- Generated by Cozy Nav -->
<META HTTP-EQUIV="Content-Type" CONTENT="text/html; charset=UTF-8">
<TITLE>Cozy Nav Bookmarks</TITLE>
<H1>Cozy Nav Bookmarks</H1>
<DL><p>
`;

    for (const cat of categories) {
      const links = db.prepare(
        'SELECT * FROM links WHERE category_id = ? AND deleted_at IS NULL ORDER BY sort_order ASC, id ASC'
      ).all(cat.id);

      if (links.length === 0) continue;

      const title = `${cat.emoji || '📁'} ${escapeHtml(cat.name)}`;
      const addDate = Math.floor(Date.now() / 1000);

      html += `  <DT><H3 ADD_DATE="${addDate}">${title}</H3>\n`;
      html += `  <DL><p>\n`;

      for (const link of links) {
        html += `    <DT><A HREF="${escapeHtml(link.url)}" ADD_DATE="${addDate}">${escapeHtml(link.name)}</A>\n`;
      }

      html += `  </DL><p>\n`;
    }

    html += `</DL><p>`;

    res.setHeader('Content-Type', 'text/html; charset=utf-8');
    res.setHeader('Content-Disposition', 'attachment; filename="cozy-nav-bookmarks.html"');
    res.send(html);
    // 操作日志：导出为敏感操作，留痕便于事后追溯数据外流
    writeLog({
      module: LOG_MODULE.IMPORT,
      action: LOG_ACTION.EXPORT,
      detail: `导出书签数据（HTML）：${categories.length} 个分类`,
      meta: { format: 'html', categories: categories.length },
    }, req);
  } catch (e) {
    // 不向客户端泄露内部错误细节，仅输出到日志
    console.log(`[${new Date().toISOString()}] [导出] [HTML] [失败] ${e.message}`);
    jsonError(res, '导出失败，请稍后重试');
  }
}

/**
 * 导入 JSON 数据
 * 支持跳过重复或覆盖现有
 */
export function importJSON(req, res) {
  const { body } = req;
  const { strategy = 'skip' } = req.body;

  if (!body || !body.categories) {
    return jsonError(res, '无效的 JSON 格式');
  }

  const { categories } = body;
  // 统计：分类新建/复用、链接新增/更新/跳过（明细最多保留 50 条避免响应体过大）
  const MAX_DETAILS = 50;
  const stats = {
    categoriesCreated: 0,
    categoriesReused: 0,
    linksCreated: 0,
    linksUpdated: 0,
    linksSkipped: 0,
    skippedDetails: [],
  };

  /** 记录一条跳过明细：累计总数，明细超上限时不再追加 */
  function pushSkip(name, url, reason) {
    stats.linksSkipped++;
    if (stats.skippedDetails.length < MAX_DETAILS) {
      stats.skippedDetails.push({ name, url, reason });
    }
  }

  try {
    // 深度校验：categories 中必须至少有一个带 name 的有效分类，否则拒绝（避免假成功）
    const hasValidCategory = categories.some((cat) => cat && typeof cat === 'object' && cat.name);
    if (!hasValidCategory) {
      return jsonError(res, '数据格式无效：未识别到任何有效分类');
    }

    db.exec('BEGIN');

    for (const cat of categories) {
      if (!cat.name) continue;

      // 查找是否已存在同名分类
      let existingCat = db.prepare('SELECT * FROM categories WHERE name = ? AND deleted_at IS NULL').get(cat.name);
      let catId;

      if (existingCat) {
        catId = existingCat.id;
        stats.categoriesReused++;
        if (strategy === 'overwrite') {
          // 覆盖策略：将分类下旧链接软删除（保留历史数据，可恢复），随后重新导入
          db.prepare('UPDATE links SET deleted_at = ? WHERE category_id = ? AND deleted_at IS NULL').run(new Date().toISOString(), existingCat.id);
          existingCat = null;
        }
      } else {
        // 新增分类（未显式传排序权重时自动排到末尾）
        const info = db.prepare(
          'INSERT INTO categories (name, subtitle, emoji, bg_color, sort_order) VALUES (?, ?, ?, ?, ?)'
        ).run(
          cat.name,
          cat.subtitle || '',
          cat.emoji || '📁',
          cat.bg_color || 'slate',
          cat.sort_order ?? db.prepare('SELECT COALESCE(MAX(sort_order), 0) + 1 AS next FROM categories WHERE deleted_at IS NULL').get().next
        );
        catId = info.lastInsertRowid;
        stats.categoriesCreated++;
      }

      // 导入链接
      if (Array.isArray(cat.links)) {
        for (const link of cat.links) {
          if (!link.name || !link.url) {
            pushSkip(link.name, link.url, '缺少名称或地址');
            continue;
          }

          // 检查链接是否已存在：优先按 URL 规范化指纹判重，无法规范化时回退精确匹配
          const normalized = normalizeUrl(link.url);
          const existingLink = normalized
            ? db.prepare(
                'SELECT * FROM links WHERE category_id = ? AND url_normalized = ? AND deleted_at IS NULL'
              ).get(catId, normalized)
            : db.prepare(
                'SELECT * FROM links WHERE category_id = ? AND url = ? AND deleted_at IS NULL'
              ).get(catId, link.url);

          if (existingLink && strategy === 'skip') {
            pushSkip(link.name, link.url, '已存在');
            continue;
          }

          if (existingLink && strategy === 'overwrite') {
            db.prepare(
              'UPDATE links SET name = ?, domain = ?, avatar_text = ?, avatar_color = ?, is_favorite = ? WHERE id = ?'
            ).run(
              link.name,
              extractDomain(link.url),
              link.avatar_text || link.name[0],
              link.avatar_color || 'slate',
              link.is_favorite ? 1 : 0,
              existingLink.id
            );
            stats.linksUpdated++;
          } else {
            // 新增链接（未显式传排序权重时自动排到该分类末尾）
            db.prepare(
              `INSERT INTO links (category_id, name, url, domain, avatar_text, avatar_color, is_pinned, is_favorite, sort_order, url_normalized)
               VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`
            ).run(
              catId,
              link.name,
              link.url,
              extractDomain(link.url),
              link.avatar_text || link.name[0],
              link.avatar_color || 'slate',
              link.is_pinned || 0,
              link.is_favorite ? 1 : 0,
              link.sort_order ?? db.prepare('SELECT COALESCE(MAX(sort_order), 0) + 1 AS next FROM links WHERE category_id = ? AND deleted_at IS NULL').get(catId).next,
              normalized
            );
            stats.linksCreated++;
          }
        }
      }
    }

    db.exec('COMMIT');
    // 操作日志：记录导入结果（含数量，异常大批量导入可事后追溯）
    writeLog({
      module: LOG_MODULE.IMPORT,
      action: LOG_ACTION.IMPORT,
      detail: `导入书签（JSON）：新建 ${stats.linksCreated} 个链接、更新 ${stats.linksUpdated} 个、跳过 ${stats.linksSkipped} 个、新建 ${stats.categoriesCreated} 个分类（策略：${strategy}）`,
      meta: {
        format: 'json', strategy,
        categoriesCreated: stats.categoriesCreated, categoriesReused: stats.categoriesReused,
        linksCreated: stats.linksCreated, linksUpdated: stats.linksUpdated, linksSkipped: stats.linksSkipped,
      },
    }, req);
    jsonSuccess(res, stats, `导入成功：新建 ${stats.categoriesCreated} 个分类，新增 ${stats.linksCreated} 个链接，更新 ${stats.linksUpdated} 个，跳过 ${stats.linksSkipped} 个`);
  } catch (e) {
    db.exec('ROLLBACK');
    // 不向客户端泄露内部错误细节，仅输出到日志
    console.log(`[${new Date().toISOString()}] [导入] [失败] ${e.message}`);
    jsonError(res, '导入失败，请检查数据后重试');
  }
}

/**
 * 导入浏览器书签 HTML
 */
export function importBookmarks(req, res) {
  const { body } = req;
  const { strategy = 'skip' } = req.body;
  const { html } = body;

  if (!html) {
    return jsonError(res, '请提供 HTML 内容');
  }

  // 统计：分类新建/复用、链接新增/更新/跳过（明细最多保留 50 条避免响应体过大）
  const MAX_DETAILS = 50;
  const stats = {
    categoriesCreated: 0,
    categoriesReused: 0,
    linksCreated: 0,
    linksUpdated: 0,
    linksSkipped: 0,
    skippedDetails: [],
  };

  /** 记录一条跳过明细：累计总数，明细超上限时不再追加 */
  function pushSkip(name, url, reason) {
    stats.linksSkipped++;
    if (stats.skippedDetails.length < MAX_DETAILS) {
      stats.skippedDetails.push({ name, url, reason });
    }
  }

  let inTransaction = false; // 事务是否已开启：BEGIN 之前的错误（如文件校验）不需要回滚
  try {
    const parsed = parseBookmarkHTML(html);
    // 无有效分类：明确提示而不是返回「导入成功 0 条」的假成功
    if (parsed.folders.length === 0) {
      return jsonError(res, '文件中没有识别到可导入的书签数据');
    }

    db.exec('BEGIN');
    inTransaction = true;

    for (const folder of parsed.folders) {
      if (!folder.name || folder.links.length === 0) continue;

      // 查找是否已存在同名分类
      let existingCat = db.prepare('SELECT * FROM categories WHERE name = ? AND deleted_at IS NULL').get(folder.name);
      let catId;

      if (existingCat) {
        catId = existingCat.id;
        stats.categoriesReused++;
        if (strategy === 'overwrite') {
          // 覆盖策略：将分类下旧链接软删除（保留历史数据，可恢复），随后重新导入
          db.prepare('UPDATE links SET deleted_at = ? WHERE category_id = ? AND deleted_at IS NULL').run(new Date().toISOString(), existingCat.id);
          existingCat = null;
        }
      } else {
        const info = db.prepare(
          'INSERT INTO categories (name, emoji, bg_color, sort_order) VALUES (?, ?, ?, ?)'
        ).run(folder.name, '📁', 'slate', db.prepare('SELECT COALESCE(MAX(sort_order), 0) + 1 AS next FROM categories WHERE deleted_at IS NULL').get().next);
        catId = info.lastInsertRowid;
        stats.categoriesCreated++;
      }

      // 导入链接
      for (const link of folder.links) {
        if (!link.name || !link.url) {
          pushSkip(link.name, link.url, '缺少名称或地址');
          continue;
        }

        // 检查链接是否已存在：优先按 URL 规范化指纹判重，无法规范化时回退精确匹配
        const normalized = normalizeUrl(link.url);
        const existingLink = normalized
          ? db.prepare(
              'SELECT * FROM links WHERE category_id = ? AND url_normalized = ? AND deleted_at IS NULL'
            ).get(catId, normalized)
          : db.prepare(
              'SELECT * FROM links WHERE category_id = ? AND url = ? AND deleted_at IS NULL'
            ).get(catId, link.url);

        if (existingLink && strategy === 'skip') {
          pushSkip(link.name, link.url, '已存在');
          continue;
        }

        if (existingLink && strategy === 'overwrite') {
          db.prepare(
            'UPDATE links SET name = ?, domain = ?, avatar_text = ? WHERE id = ?'
          ).run(link.name, extractDomain(link.url), link.name[0], existingLink.id);
          stats.linksUpdated++;
        } else {
          // 新增链接（未显式传排序权重时自动排到该分类末尾）
          db.prepare(
            `INSERT INTO links (category_id, name, url, domain, avatar_text, avatar_color, sort_order, url_normalized)
             VALUES (?, ?, ?, ?, ?, ?, ?, ?)`
          ).run(catId, link.name, link.url, extractDomain(link.url), link.name[0], 'slate', db.prepare('SELECT COALESCE(MAX(sort_order), 0) + 1 AS next FROM links WHERE category_id = ? AND deleted_at IS NULL').get(catId).next, normalized);
          stats.linksCreated++;
        }
      }
    }

    db.exec('COMMIT');
    // 操作日志：记录导入结果（含数量，异常大批量导入可事后追溯）
    writeLog({
      module: LOG_MODULE.IMPORT,
      action: LOG_ACTION.IMPORT,
      detail: `导入书签（HTML）：新建 ${stats.linksCreated} 个链接、更新 ${stats.linksUpdated} 个、跳过 ${stats.linksSkipped} 个、新建 ${stats.categoriesCreated} 个分类（策略：${strategy}）`,
      meta: {
        format: 'html', strategy,
        categoriesCreated: stats.categoriesCreated, categoriesReused: stats.categoriesReused,
        linksCreated: stats.linksCreated, linksUpdated: stats.linksUpdated, linksSkipped: stats.linksSkipped,
      },
    }, req);
    jsonSuccess(res, stats, `导入成功：新建 ${stats.categoriesCreated} 个分类，新增 ${stats.linksCreated} 个链接，更新 ${stats.linksUpdated} 个，跳过 ${stats.linksSkipped} 个`);
  } catch (e) {
    // 仅在事务已开启时回滚，避免「无活动事务」错误覆盖原始错误
    if (inTransaction) db.exec('ROLLBACK');
    // 文件特征校验失败：向客户端返回具体原因；其余内部错误不泄露细节
    if (e.code === 'INVALID_BOOKMARK_FILE') {
      return jsonError(res, e.message);
    }
    // 不向客户端泄露内部错误细节，仅输出到日志
    console.log(`[${new Date().toISOString()}] [导入] [HTML] [失败] ${e.message}`);
    jsonError(res, '导入失败，请检查数据后重试');
  }
}

/**
 * 解析浏览器书签 HTML（兼容 Chrome / Edge / Firefox / Safari 导出的 Netscape 书签格式）
 * - 递归处理 <DL>/<DT> 嵌套结构，嵌套文件夹拍平为「父/子」独立分类（策略 A）
 * - 属性差异统一处理：ADD_DATE / LAST_MODIFIED 均忽略，ICON(base64) / ICON_URI / FOLDED 直接跳过
 * - 特征校验：必须包含 Netscape 书签 DOCTYPE 或至少一个 <A HREF，否则抛错拒绝导入
 */
export function parseBookmarkHTML(html) {
  // 移除注释，避免干扰结构解析
  const cleaned = html.replace(/<!--[\s\S]*?-->/g, '');

  // 特征校验：识别浏览器导出的书签文件，普通 HTML 不允许混入
  if (!/(<!DOCTYPE\s+NETSCAPE-Bookmark-file-1)|<A\s+HREF=/i.test(cleaned)) {
    throw Object.assign(new Error('不是有效的浏览器书签文件，请确认文件由 Chrome / Edge / Firefox / Safari 导出'), { code: 'INVALID_BOOKMARK_FILE' });
  }

  const folders = []; // 拍平后的分类 [{ name, links }]

  // 从 dlTagIdx（指向 '<DL'）解析一个容器，返回 { nextPos, links }
  // links 为该容器内直接链接（不属于任何子文件夹），供父文件夹归集；
  // 容器内嵌套子文件夹则递归解析，并即时以「父/子」路径拍平入库
  function walkDL(dlTagIdx, path) {
    let pos = cleaned.indexOf('>', dlTagIdx) + 1; // 跳过 <DL 开始标签
    const links = [];

    for (;;) {
      // 容器内最近的 <DT 与 </DL，谁先出现决定后续走向
      const dtIdx = cleaned.toLowerCase().indexOf('<dt', pos);
      const dlEndIdx = cleaned.toLowerCase().indexOf('</dl', pos);
      if (dlEndIdx >= 0 && (dtIdx < 0 || dlEndIdx < dtIdx)) {
        return { nextPos: cleaned.indexOf('>', dlEndIdx) + 1, links };
      }
      if (dtIdx < 0) return { nextPos: cleaned.length, links };

      const content = cleaned.slice(cleaned.indexOf('>', dtIdx + 3) + 1);

      if (/^\s*<H3\b/i.test(content)) {
        // 文件夹条目：提取名称，检查其内容是否为嵌套 <DL>
        const h3Match = content.match(/<H3\b[^>]*>([\s\S]*?)<\/H3>/i);
        if (!h3Match) { pos = dtIdx + 3; continue; }
        const rawName = h3Match[1].replace(/<[^>]*>/g, '').trim();
        // 清理 emoji / 特殊字符前缀（浏览器导出常带 📁 等图标）
        const cleanName = rawName.replace(/^[^\w\u4e00-\u9fff]+/, '').trim() || '未命名';
        const childPath = path ? `${path}/${cleanName}` : cleanName;
        const afterH3 = cleaned.indexOf('>', dtIdx + 3) + 1 + h3Match.index + h3Match[0].length;
        const nextDlIdx = cleaned.toLowerCase().indexOf('<dl', afterH3);
        const nextDlEndIdx = cleaned.toLowerCase().indexOf('</dl', afterH3);

        if (nextDlIdx >= 0 && (nextDlEndIdx < 0 || nextDlIdx < nextDlEndIdx)) {
          // 有子内容：递归解析，子容器直接链接归入「父/子」分类
          const child = walkDL(nextDlIdx, childPath);
          if (child.links.length) folders.push({ name: childPath, links: child.links });
          pos = child.nextPos;
        } else {
          pos = afterH3; // 空文件夹：跳过
        }
      } else if (/^\s*<A\b/i.test(content)) {
        // 链接条目：提取 HREF 与显示名
        const aMatch = content.match(/<A\b[^>]*HREF="([^"]*)"[^>]*>([\s\S]*?)<\/A>/i);
        if (!aMatch) { pos = dtIdx + 3; continue; }
        const name = aMatch[2].replace(/<[^>]*>/g, '').trim();
        links.push({ url: aMatch[1], name: name || aMatch[1] });
        pos = cleaned.indexOf('>', dtIdx + 3) + 1 + aMatch.index + aMatch[0].length;
      } else {
        pos = dtIdx + 3; // 其它标签（<HR>、<P> 等）：跳过
      }
    }
  }

  // 顶层容器（浏览器导出的根 <DL>），顶层裸链接不归属任何分类，忽略
  const rootDlIdx = cleaned.toLowerCase().indexOf('<dl');
  if (rootDlIdx >= 0) walkDL(rootDlIdx, '');

  return { folders };
}

/**
 * 提取域名
 */
function extractDomain(url) {
  try {
    return new URL(url).hostname;
  } catch {
    return '';
  }
}

/**
 * HTML 转义
 */
function escapeHtml(str) {
  return str.replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#39;');
}